/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital_management_system.views;


import hospital_management_system.models.InvoiceModel;
import hospital_management_system.models.Billing;
import hospital_management_system.models.Invoice;
import hospital_management_system.MysqlConnect;
import hospital_management_system.controllers.InvoiceController;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

import java.awt.Font;
import java.sql.*;

/**
 *
 * @author yc
 */
public class GUI_Invoice extends javax.swing.JFrame {

    private String patientId;
    private String invoiceId;

    private MysqlConnect db;

    /**
     * Creates new form Invoice
     */
    public GUI_Invoice(String invoiceId, String patientId) {
        db = new MysqlConnect();
        this.patientId = patientId;
        this.invoiceId = invoiceId;

        initComponents();
        
        // Call method to display data
        displayInvoiceData(invoiceId, patientId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PatientID = new javax.swing.JPanel();
        InvoiceNo_label = new javax.swing.JLabel();
        InvoiceDate_label = new javax.swing.JLabel();
        InvoiceDue_label = new javax.swing.JLabel();
        From_address = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Total_label = new javax.swing.JLabel();
        AmountPaid_label = new javax.swing.JLabel();
        BalanceDue_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        From_address1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PatientName = new javax.swing.JLabel();
        InvoiceNo = new javax.swing.JLabel();
        InvoiceDate = new javax.swing.JLabel();
        InvoiceDue = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        AmountPaid = new javax.swing.JLabel();
        BalanceDue = new javax.swing.JLabel();

        PatientID_display = new javax.swing.JLabel();
        PatientName_display = new javax.swing.JLabel();
        InvoiceNo_display = new javax.swing.JLabel();
        InvoiceDate_display = new javax.swing.JLabel();
        InvoiceDue_display = new javax.swing.JLabel();
        TotalAmount_display = new javax.swing.JLabel();
        AmountPaid_display = new javax.swing.JLabel();
        BalanceDue_display = new javax.swing.JLabel();
        InvoiceTable = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jTextField2.setText("jTextField2");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PatientID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Invoice", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        InvoiceNo_label.setText("Invoice no:");

        InvoiceDate_label.setText("Invoice date:");

        InvoiceDue_label.setText("Due:");

        From_address.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        From_address.setText("From:");

        InvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
           
            },
            new String [] {
                "Description", "RM / item", "QTY", "Total"
            }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // All cells are non-editable
            }
        });
        jScrollPane2.setViewportView(InvoiceTable);

        Total_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Total_label.setText("Total:");

        AmountPaid_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AmountPaid_label.setText("Amount Paid:");

        BalanceDue_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BalanceDue_label.setText("Balance Due:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("WellSpring Hospital");

        From_address1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        From_address1.setText("To:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("   Patient ID: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("   Name: ");

        jLabel4.setText("456 Jalan Tun Razak,");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); 

        jLabel5.setText("50400 Kuala Lumpur,");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); 

        jLabel6.setText("Malaysia");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); 

        PatientID_display.setText(" ");
        PatientID_display.setFont(new java.awt.Font("Segoe UI", 0, 12));

        PatientName_display.setText(" ");
        PatientName_display.setFont(new java.awt.Font("Segoe UI", 0, 12));

        InvoiceNo_display.setText(" ");
        InvoiceNo_display.setFont(new java.awt.Font("Segoe UI", 0, 12));

        InvoiceDate_display.setText(" ");
        InvoiceDate_display.setFont(new java.awt.Font("Segoe UI", 0, 12));

        InvoiceDue_display.setText(" ");
        InvoiceDue_display.setFont(new java.awt.Font("Segoe UI", 0, 12));

        TotalAmount_display.setText(" ");
        TotalAmount_display.setFont(new java.awt.Font("Segoe UI", 0, 12));

        AmountPaid_display.setText(" ");
        AmountPaid_display.setFont(new java.awt.Font("Segoe UI", 0, 12));

        BalanceDue_display.setText(" ");
        BalanceDue_display.setFont(new java.awt.Font("Segoe UI", 0, 12));

        javax.swing.GroupLayout PatientIDLayout = new javax.swing.GroupLayout(PatientID);
        PatientID.setLayout(PatientIDLayout);
        PatientIDLayout.setHorizontalGroup(
            PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientIDLayout.createSequentialGroup()
                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PatientIDLayout.createSequentialGroup()
                                .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatientIDLayout.createSequentialGroup()
                                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(PatientName_display, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                            .addComponent(PatientID_display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PatientName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))))
                            .addGroup(PatientIDLayout.createSequentialGroup()
                                .addComponent(From_address, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(From_address1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InvoiceDate_label)
                            .addComponent(InvoiceNo_label)
                            .addComponent(InvoiceDue_label, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InvoiceDue_display, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(InvoiceDate_display, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InvoiceNo_display, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InvoiceNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InvoiceDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InvoiceDue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PatientIDLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PatientIDLayout.createSequentialGroup()
                                .addComponent(BalanceDue_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PatientIDLayout.createSequentialGroup()
                                        .addComponent(BalanceDue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(BalanceDue_display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PatientIDLayout.createSequentialGroup()
                                    .addComponent(AmountPaid_label, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(AmountPaid_display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PatientIDLayout.createSequentialGroup()
                                    .addComponent(Total_label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(58, 58, 58)
                                    .addComponent(TotalAmount_display, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AmountPaid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        PatientIDLayout.setVerticalGroup(
            PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InvoiceNo_label)
                    .addComponent(From_address)
                    .addComponent(From_address1)
                    .addComponent(InvoiceNo)
                    .addComponent(InvoiceNo_display))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientIDLayout.createSequentialGroup()
                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(PatientID_display))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)))
                    .addGroup(PatientIDLayout.createSequentialGroup()
                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvoiceDate_label)
                            .addComponent(InvoiceDate)
                            .addComponent(InvoiceDate_display))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvoiceDue_label)
                            .addComponent(InvoiceDue)
                            .addComponent(InvoiceDue_display))))
                .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientIDLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(PatientName_display)))
                    .addGroup(PatientIDLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PatientName)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total_label)
                    .addComponent(Total)
                    .addComponent(TotalAmount_display))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AmountPaid)
                    .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AmountPaid_label)
                        .addComponent(AmountPaid_display)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PatientIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BalanceDue_label)
                    .addComponent(BalanceDue)
                    .addComponent(BalanceDue_display))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Method to fetch and display invoice data
    public void displayInvoiceData(String invoiceId, String patientId) {
        // Prepare the query
        String query = "SELECT Invoice.InvoiceID, Invoice.InvoiceDate, Invoice.InvoiceDue, Invoice.TotalPayment, " +
                       "Invoice.AmountPaid, Invoice.BalanceDue, Patients.patient_name " +
                       "FROM Invoice " +
                       "JOIN Patients ON Invoice.PatientID = Patients.patient_id " +
                       "WHERE Invoice.InvoiceID = '" + invoiceId + "' AND Invoice.PatientID = '" + patientId +"'";

        try (ResultSet rs = db.executeQuery(query)) {
            if (rs.next()) {
                // Assuming columns names in the database
                String invoiceNo = rs.getString("InvoiceID");
                String patientName = rs.getString("patient_name");
                String invoiceDate = rs.getString("InvoiceDate");
                String invoiceDue = rs.getString("InvoiceDue");
                String totalAmount = rs.getString("TotalPayment");
                String amountPaid = rs.getString("AmountPaid");
                String balanceDue = rs.getString("BalanceDue");

                // Set data to the labels
                InvoiceNo_display.setText(invoiceNo);
                InvoiceDate_display.setText(invoiceDate);
                InvoiceDue_display.setText(invoiceDue);
                TotalAmount_display.setText(totalAmount);
                AmountPaid_display.setText(amountPaid);
                BalanceDue_display.setText(balanceDue);
                PatientName_display.setText("   " + patientName);
                PatientID_display.setText("    " + patientId);
                
                // Call method to fill invoice table
                fillInvoiceTable(invoiceId);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Method to fill invoice table with service details
    private void fillInvoiceTable(String invoiceId) {
        // Prepare query to fetch service details for the invoice
        String query = "SELECT ServicesDescription, CostPerService, Quantity, TotalPayment FROM Billing WHERE InvoiceID = '" + invoiceId + "'";
        DefaultTableModel model = (DefaultTableModel) InvoiceTable.getModel();

        try (ResultSet rs = db.executeQuery(query)) {
            // Clear existing table rows
            model.setRowCount(0);

            while (rs.next()) {
                String description = rs.getString("ServicesDescription");
                double costPerService = rs.getDouble("CostPerService");
                int quantity = rs.getInt("Quantity");
                double totalCost = rs.getDouble("TotalPayment");

                // Add row to table
                model.addRow(new Object[]{description, costPerService, quantity, totalCost});
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error fetching invoice items", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountPaid;
    private javax.swing.JLabel AmountPaid_display;
    private javax.swing.JLabel AmountPaid_label;
    private javax.swing.JLabel BalanceDue;
    private javax.swing.JLabel BalanceDue_display;
    private javax.swing.JLabel BalanceDue_label;
    private javax.swing.JLabel From_address;
    private javax.swing.JLabel From_address1;
    private javax.swing.JLabel InvoiceDate;
    private javax.swing.JLabel InvoiceDate_display;
    private javax.swing.JLabel InvoiceDate_label;
    private javax.swing.JLabel InvoiceDue;
    private javax.swing.JLabel InvoiceDue_display;
    private javax.swing.JLabel InvoiceDue_label;
    private javax.swing.JLabel InvoiceNo;
    private javax.swing.JLabel InvoiceNo_display;
    private javax.swing.JLabel InvoiceNo_label;
    private javax.swing.JTable InvoiceTable;
    private javax.swing.JPanel PatientID;
    private javax.swing.JLabel PatientID_display;
    private javax.swing.JLabel PatientName;
    private javax.swing.JLabel PatientName_display;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel TotalAmount_display;
    private javax.swing.JLabel Total_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
